name: Asymmetric Curve CI

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libgmp-dev libmpfr-dev libssl-dev libgtest-dev cmake

      - name: Checkout RELIC
        uses: actions/checkout@v4
        with:
          repository: relic-toolkit/relic
          path: relic

      - name: Install RELIC asymmetric curve
        run: |
          mkdir relic/build
          cd relic/build
          ../preset/gmp-pbc-bls381.sh ..
          sudo make
          sudo make install

      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Build and install project
        run: |
          mkdir build
          cd build
          cmake ..
          sudo make
          sudo make install

      - name: Run tests
        run: |
          cd build
          ctest

      - name: Build demo
        run: |
          mkdir demo/build
          cd demo/build
          cmake ..
          sudo make

      - name: Run demo
        run: |
          cd demo/build
          ./demo
